[supervisord]
nodaemon=true
logfile=/workspace/.logs/services/supervisord.log
pidfile=/run/quiver/supervisord.pid
childlogdir=/workspace/.logs/services

[unix_http_server]
file=/run/quiver/supervisor.sock
chmod=0700

[supervisorctl]
serverurl=unix:///run/quiver/supervisor.sock

[include]
files = /etc/supervisor/conf.d/*.conf
