"""Generate Supervisor programs from Quiver's read-only runtime config."""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

PROGRAMS = {
    "vpn": "/usr/local/bin/quiver-vpn",
    "gui": "/usr/local/bin/quiver-gui",
}


def main() -> None:
    if len(sys.argv) != 3:
        raise SystemExit("usage: generate-supervisor.py CONFIG OUTPUT")
    config_path, output_path = map(Path, sys.argv[1:])
    config = yaml.safe_load(config_path.read_text())
    if not isinstance(config, dict):
        raise SystemExit("runtime config must be a mapping")

    vpn_enabled = bool((config.get("vpn") or {}).get("enabled", False))
    lines = [
        "; Generated by quiver-entrypoint. Do not edit.",
        "[program:gui]",
        f"command={PROGRAMS['gui']}",
        "autostart=false",
        "autorestart=false",
        "stdout_logfile=/workspace/.logs/services/gui.log",
        "stderr_logfile=/workspace/.logs/services/gui.log",
        "stopasgroup=true",
        "killasgroup=true",
    ]
    if vpn_enabled:
        lines.extend(
            [
                "",
                "[program:vpn]",
                f"command={PROGRAMS['vpn']}",
                "autostart=true",
                "autorestart=unexpected",
                "startretries=3",
                "stdout_logfile=/workspace/.logs/services/vpn.log",
                "stderr_logfile=/workspace/.logs/services/vpn.log",
                "stopasgroup=true",
                "killasgroup=true",
            ]
        )
    output_path.write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
