# syntax=docker/dockerfile:1
# Build from the packaged resource root: docker build -f images/base/Dockerfile.amd64 .
FROM archlinux:base-devel

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN sed -i '/^\[options\]/a DisableSandbox' /etc/pacman.conf \
    && pacman-key --init \
    && pacman-key --populate archlinux \
    && pacman -Syu --noconfirm --needed \
        asciinema ca-certificates curl eza fish firefox git go iproute2 iptables-nft neovim nftables \
        openvpn python python-pip python-pyyaml starship sudo supervisor tigervnc tmux util-linux \
        wireguard-tools xorg-xauth xterm xfce4 xfce4-terminal zoxide zsh \
    && python -m venv /opt/quiver-websockify \
    && /opt/quiver-websockify/bin/pip install --no-cache-dir websockify \
    && ln -s /opt/quiver-websockify/bin/websockify /usr/local/bin/websockify \
    && git clone --depth 1 https://github.com/novnc/noVNC.git /opt/novnc \
    && git clone --depth 1 https://github.com/WireGuard/wireguard-go.git /tmp/wireguard-go \
    && (cd /tmp/wireguard-go && go build -o /usr/local/bin/wireguard-go) \
    && rm -rf /tmp/wireguard-go \
    && curl --fail --location --silent --show-error --retry 5 --retry-all-errors \
        https://blackarch.org/strap.sh --output /tmp/strap.sh \
    && chmod +x /tmp/strap.sh \
    && /tmp/strap.sh \
    && rm -f /tmp/strap.sh \
    && pacman -S --noconfirm --needed blackarch-keyring \
    && pacman -Scc --noconfirm

COPY images/common/entrypoint/quiver-entrypoint /usr/local/bin/quiver-entrypoint
COPY images/common/shell/quiver-record-shell /usr/local/bin/quiver-record-shell
COPY images/common/shell/quiver-audit-hook.zsh /usr/local/lib/quiver/quiver-audit-hook.zsh
COPY images/common/shell/quiver-audit-hook.fish /usr/local/lib/quiver/quiver-audit-hook.fish
COPY images/common/supervisor/quiver-vpn /usr/local/bin/quiver-vpn
COPY images/common/supervisor/quiver-killswitch.py /usr/local/lib/quiver/quiver-killswitch.py
COPY images/common/supervisor/killswitch.py /usr/local/lib/quiver/killswitch.py
COPY images/common/gui/quiver-gui /usr/local/bin/quiver-gui
COPY images/common/gui/assets/quiver-background.png /usr/share/backgrounds/quiver/background.png
COPY images/common/supervisor/supervisord.conf /etc/supervisor/supervisord.conf
COPY images/common/entrypoint/generate-supervisor.py /usr/local/lib/quiver/generate-supervisor.py
COPY images/common/entrypoint/image.json /etc/quiver/image.json
COPY packages/base.yaml /etc/quiver/packages/base.yaml

RUN install -d -m 0755 /workspace /run/quiver /etc/supervisor/conf.d /opt \
    && printf '%s\n' '[[ -n ${QUIVER_SESSION_ID:-} ]] && source /usr/local/lib/quiver/quiver-audit-hook.zsh' > /etc/zsh/zshrc \
    && if [[ -d /usr/share/webapps/novnc ]]; then ln -s /usr/share/webapps/novnc /opt/novnc; fi \
    && test -d /opt/novnc \
    && chmod 0755 /usr/local/bin/quiver-entrypoint /usr/local/bin/quiver-record-shell \
        /usr/local/bin/quiver-vpn /usr/local/bin/quiver-gui \
        /usr/local/lib/quiver/quiver-killswitch.py \
    && chmod 0644 /usr/local/lib/quiver/quiver-audit-hook.zsh \
        /usr/local/lib/quiver/quiver-audit-hook.fish \
        /usr/local/lib/quiver/generate-supervisor.py /usr/local/lib/quiver/killswitch.py \
        /etc/quiver/image.json /etc/quiver/packages/base.yaml

ENV SHELL=/usr/bin/fish

WORKDIR /workspace
ENTRYPOINT ["/usr/local/bin/quiver-entrypoint"]
